name: base
channels:
  - nvidia
  - pytorch3d
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytorch
  - pytorch-cuda=11.8
  - pytorch3d
  - pip
  - pip:
    - numpy==1.23.1
    - -r requirements.txt
    - submodules/simple-knn
    - submodules/diff-gaussian-rasterization
# git example    - git+https://github.com/XPixelGroup/BasicSR.git
